product_management/urls.py
from django.urls import path
from product_management.views import *


app_name = 'product_management'

urlpatterns=[
    path('products/', create_product_view, name='product'),
    path('<slug>/edit', edit_product_view, name='edit'),
    path('<slug>/delete', delete_product_view, name='delete'),
]

sms/urls.py
from django.contrib import admin
from django.urls import path,include
from gui.views import *
from account.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),

    # password change links:
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path('product_management/', include('product_management.urls', 'product_management')),
    path(('sales_management/'), include('sales_management.urls', 'sales_management')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

gui/models.py
# from django.db import models
#
#
# # PRIORITY = [('L', 'Low'),
# #             ('M', 'Medium'),
# #             ('H', 'High'),
# # ]
#
# class Products(models.Model):
#     name           =models.CharField(max_length=100)
#     company        =models.CharField(max_length=400)
#     type           =models.CharField(max_length=400)
#     cost           =models.FloatField()
#
#     def __str__(self):
#         return self.name

    # class Meta:
    #     verbose_name = "The Question"
    #     verbose_name_plural = 'Peoples Question'

gui/views.py
from django.shortcuts import render
from django.http import HttpResponse
from account.models import Account
from product_management.models import Products
from product_management.views import get_product_queryset
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

PRODUCTS_PER_PAGE = 5

def home_screen_view(request, *args, **kwargs):
    context = {}

    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    accounts = Account.objects.all()
    # products = Products.objects.all()
    product = get_product_queryset(query)
    # context['products'] = products

    # Pagination
    page = request.GET.get('page', 1)
    product_paginator = Paginator(product, PRODUCTS_PER_PAGE)

    try:
        product = product_paginator.page(page)
    except PageNotAnInteger:
        product = product_paginator.page(PRODUCTS_PER_PAGE)
    except EmptyPage:
        product = product_paginator.page(product_paginator.num_pages)

    context['product'] = product

    # Pagination
    page = request.GET.get('page', 1)
    accounts_paginator = Paginator(accounts, PRODUCTS_PER_PAGE)

    try:
        accounts = accounts_paginator.page(page)
    except PageNotAnInteger:
        accounts = accounts_paginator.page(PRODUCTS_PER_PAGE)
    except EmptyPage:
        accounts = accounts_paginator.page(accounts_paginator.num_pages)

    context['accounts'] = accounts

    return render(request, 'gui/home.html', context)

gui/templates/gui/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'snippets/home_css.html' %}

<div class="background left-column col-lg-11 offset-lg-1" >
{#    <div class = "container">#}
{#        <div class="d-flex flex-column">#}
{#            {% if request.user.is_authenticated %}#}
{#                <h3>Products list</h3>#}
{#                    {% for product in products %}#}
{#                        <p>{{ product }}</p>#}
{#                    {% endfor %}#}
{#            {% else %}#}
{#                    {% for account in accounts %}#}
{#                        <p>{{ account.username }} | {{ account.date_joined }} {{ account.active }}</p>#}
{#                    {% endfor%}#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{% if request.user.is_authenticated %}

    <div class="store-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Store Management System</h1>
      <p class="lead">Product records:</p>
    </div>

    <div class="search-bar mb-sm-2 m-auto">
        <form method="get">
            <input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
        </form>
    </div>

{% if product %}
   <table class="table table-striped ">
        <thead>
        <tr>
            <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Company</th>
          <th scope="col">Type</th>
          <th scope="col">Cost</th>
          <th scope="col">Stock</th>
        </tr>
        </thead>
        <tbody>
        {% for products in product %}
            <tr>
                <th scope="row">></th>
                <td>{{ products.name }}</td>
                <td>{{ products.company }}</td>
                <td>{{ products.type }}</td>
                <td>{{ products.cost }}</td>
                <td>{{ products.stock }}</td>
                <td><a href="{% url 'product_management:edit' products.slug %}">Update</a></td>
                <td><a href="{% url 'product_management:delete' products.slug %}">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'product_management/snippets/product_pagination.html'%}
{% else %}
    <div class="container">
        <div class="row">
            <div class="card m-auto">
                <div class="card-body mt-2 mb-2">
                    <h2 class="card-title">
                        No results
                    </h2>
                    <p class="card-text">There were no results matching your search: "{{ query }}".</p>
                </div>
            </div>
        </div>
    </div>
{% endif %}
    <div class="bottompad">
    </div>
{% else %}

    <div class="store-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Store Management System</h1>
      <p class="lead">Staff Members</p>
    </div>

    <table class="table table-striped ">
        <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Date joined</th>
          <th scope="col">Last login</th>
        </tr>
        </thead>
        <tbody>
        {% for account in accounts %}
            <tr>
                <th scope="row">{{ account.id }}</th>
                <td>{{ account.username }}</td>
                <td>{{ account.email }}</td>
                <td>{{ account.date_joined }}</td>
                <td>{{ account.last_login }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'gui/snippets/accounts_pagination.html' %}
    <div class="bottompad">
    </div>
{% endif %}
</div>

<script type="text/javascript">
    document.getElementById('id_q').value = '{{ query }}'
</script>

{% endblock content %}