product_management/urls.py
from django.urls import path
from product_management.views import *


app_name = 'product_management'

urlpatterns=[
    path('products/', create_product_view, name='product'),
    path('<slug>/edit', edit_product_view, name='edit'),
    path('<slug>/delete', delete_product_view, name='delete'),
]

sms/urls.py
from django.contrib import admin
from django.urls import path,include
from gui.views import *
from account.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),

    # password change links:
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path('product_management/', include('product_management.urls', 'product_management')),
    path(('sales_management/'), include('sales_management.urls', 'sales_management')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

product_management/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver


class Products(models.Model):
    name            =models.CharField(max_length=100, null=False, blank=False, unique=True)
    company         =models.CharField(max_length=400, null=False, blank=False)
    type            =models.CharField(max_length=400, null=False, blank=False)
    cost            =models.FloatField()
    stock           =models.IntegerField()
    # author          =models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug            =models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Products"
        verbose_name_plural = 'Product'



def pre_save_products_receiver(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)

pre_save.connect(pre_save_products_receiver, sender=Products)

product_management/forms.py
from django import forms
from product_management.models import Products

class CreateAddProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['name', 'company', 'type', 'cost', 'stock']

class UpdateAddProductsForm(forms.ModelForm):

    class Meta:
        model = Products
        fields = ['name', 'company', 'type', 'cost', 'stock']

    def save(self, commit=True):
        add_product = self.instance
        # add_product.id = self.cleaned_data['id']
        add_product.name = self.cleaned_data['name']
        add_product.company = self.cleaned_data['company']
        add_product.type = self.cleaned_data['type']
        add_product.cost = self.cleaned_data['cost']
        add_product.stock = self.cleaned_data['stock']

        if commit:
            add_product.save()
        return add_product

product_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product_management.models import *
from product_management.forms import *
from account.models import *
from django.db.models import Q


def create_product_view(request):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    if request.POST:
        form = CreateAddProductsForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            context['create_product_view_form'] = form
    else:
            form = CreateAddProductsForm()
            context['create_product_view_form'] = form

    return render(request, "product_management/add_products.html", context)

def edit_product_view(request, slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    add_product = get_object_or_404(Products, slug=slug)
    if request.POST:
        form = UpdateAddProductsForm(request.POST or None, instance=add_product)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = 'Updated'
            add_product = obj

    form = UpdateAddProductsForm(
            initial={
                    'name': add_product.name,
                    'company': add_product.company,
                    'type': add_product.type,
                    'cost': add_product.cost,
                    'stock': add_product.stock,
            }
         )

    context['form'] = form
    return render(request, 'product_management/edit_product.html', context)

def delete_product_view(request, slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    add_product = get_object_or_404(Products, slug=slug)
    if request.POST:
        form = UpdateAddProductsForm(request.POST , instance=add_product)
        add_product.delete()
        context['success_message'] = 'Deleted Successfully'

    form = UpdateAddProductsForm(
            initial={
                'id': add_product.id,
                'name': add_product.name,
                'company': add_product.company,
                'type': add_product.type,
                'cost': add_product.cost,
                'stock': add_product.stock,
            }
        )

    context['form'] = form
    return render(request, 'product_management/delete_product.html', context)

def get_product_queryset(query=None):
    queryset = []
    queries = query.split(' ')#hello world = [hello, world]
    for q in queries:
        posts = Products.objects.filter(
                Q(name__icontains=q) |
                Q(company__icontains=q) |
                Q(type__icontains=q)
            ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))

product_management/templates/product_management/add_products.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post">{% csrf_token %}

				<!-- name -->
				<div class="form-group">
					<label for="id_name">Name</label>
					<input class="form-control" type="text" name="name" id="id_name" placeholder="Product Name" required autofocus>
				</div>

				<!-- company -->
				<div class="form-group">
					<label for="id_company">Company</label>
					<input class="form-control" type="text" name="company" id="id_company" placeholder="Product Company" required>
				</div>

                <!-- Type -->
				<div class="form-group">
					<label for="id_type">Type</label>
					<input class="form-control" type="text" name="type" id="id_type" placeholder="Product Type" required>
				</div>

                <!-- cost -->
				<div class="form-group">
					<label for="id_cost">Cost</label>
					<input class="form-control" type="text" name="cost" id="id_cost" placeholder="Product Cost" required>
				</div>

                <!-- stock -->
				<div class="form-group">
					<label for="id_stock">Stock</label>
					<input class="form-control" type="text" name="stock" id="id_stock" placeholder="Product Stock" required>
				</div>


				<!-- Submit btn -->
                <div class="d-flex flex-row">
                    <a href="{% url 'home' %}"><button class="submit-button btn btn-lg btn-primary btn-block " type="submit"><a style="color: white" href="{% url 'home' %}">Add</a></button>
                </div>
			</form>
			</form>
		</div>
	</div>
</div>




{% endblock content %}

product_management/templates/product_management/delete_product.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    <h3>Are you sure u want to delete this menu from the list??</h3>
                </div>

                <table class="table table-striped ">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Company</th>
                      <th scope="col">Type</th>
                      <th scope="col">Cost</th>
                      <th scope="col">Stock</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">{{ form.initial.id }}</th>
                            <td>{{ form.initial.name }}</td>
                            <td>{{ form.initial.company }}</td>
                            <td>{{ form.initial.type }}</td>
                            <td>{{ form.initial.cost }}</td>
                            <td>{{ form.initial.stock }}</td>
                        </tr>
                    </tbody>
                </table>

                {% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Delete</button>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

product_management/templates/product_management/edit_product.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                <!-- name -->
				<div class="form-group">
					<label for="id_name">Name</label>
					<input class="form-control" type="text" name="name" id="id_name" placeholder="Product Name" value="{{ form.initial.name }}" required autofocus>
				</div>

				<!-- company -->
				<div class="form-group">
					<label for="id_company">Company</label>
					<input class="form-control" type="text" name="company" id="id_company" placeholder="Product Company" value="{{ form.initial.company }}" required>
				</div>

                <!-- Type -->
				<div class="form-group">
					<label for="id_type">Type</label>
					<input class="form-control" type="text" name="type" id="id_type" placeholder="Product Type" value="{{ form.initial.type }}" required>
				</div>

                <!-- cost -->
				<div class="form-group">
					<label for="id_cost">Cost</label>
					<input class="form-control" type="text" name="cost" id="id_cost" placeholder="Product Cost" value="{{ form.initial.cost }}" required>
				</div>

                <!-- stock -->
				<div class="form-group">
					<label for="id_stock">Stock</label>
					<input class="form-control" type="text" name="stock" id="id_stock" placeholder="Product Stock" value="{{ form.initial.stock }}" required>
				</div>

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>
		</div>
	</div>
</div>

{% endblock content %}