product_management/urls.py
from django.urls import path
from product_management.views import *


app_name = 'product_management'

urlpatterns=[
    path('products/', create_product_view, name='product'),
    path('<slug>/edit', edit_product_view, name='edit'),
    path('<slug>/delete', delete_product_view, name='delete'),
]

sales_management/urls.py
from django.urls import path
from sales_management.views import *

app_name = "sales_management"

urlpatterns = [
    path('customer', create_customer_view, name='customer'),
]

sms/urls.py
from django.contrib import admin
from django.urls import path,include
from gui.views import *
from account.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('must_authenticate/', must_authenticate_view, name='must_authenticate'),

    # password change links:
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path('product_management/', include('product_management.urls', 'product_management')),
    path(('sales_management/'), include('sales_management.urls', 'sales_management')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/snippets/base_css.html
<style type="text/css">
    body{
        background-color: #f2f2f2;
    }
</style>

templates/snippets/footer.html
<style type="text/css">
    .footer{
        min-height: 100px;
        {#border: 1px solid #000000;#}
    }
</style>

<!-- footer -->
<div class="d-flex flex-row align-items-center footer bg-white shadow-lg">
    <p class="m-auto">Store Management System | 2020</p>
</div>
<!-- End footer -->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

templates/snippets/header.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<style type="text/css">
    @media (min-width: 768px) {
      html {
        font-size: 16px;
      }
    }

    .container{
        max-width: 960px;
    }

    .store-header {
      max-width: 1000px;
    }
</style>

<!-- HEADER -->
<div class="navbar sticky-top d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

        {% if request.user.is_authenticated %}
            <h5 class="my-0 mr-md-auto font-weight-normal"><img class="img-fluid mx-auto d-block" src="{% static 'maxresdefault.jpg' %}" alt="store logo" width="60" ></h5>
{#            <h5 class="mr-md-auto font-weight-normal">Welcome: <a href="{% url 'account' %}">{{ request.user.username }}</a> </h5>#}
        {% else %}
              <h5 class="my-0 mr-md-auto font-weight-normal">Store Management System</h5>
        {% endif %}

  <nav class="my-2 my-md-0 mr-md-3">
      {% if request.user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
            <a class="p-2 text-dark" href="{% url 'account' %}">Account</a>
            <a class="p-2 text-dark" href="{% url 'sales_management:customer' %}">Sales Management</a>
            <a class="p-2 text-dark" href="{% url 'product_management:product' %}">Product Management</a>
            <a class="btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
      {% else %}
            <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
            <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
            <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
      {% endif %}
  </nav>
</div>
<!-- END HEADER -->

templates/snippets/home_css.html
<style type="text/css">
    .background{
        height: auto;
        width: auto;
        background: whitesmoke;
        box-shadow: 0 25px 30px rgba(0, 0, 0, .5);
    }
    .bottompad{
        padding-bottom: 50px;
    }
    .search-bar{
        max-width: 500px;
        width: 100%;
    }
    .card{
        max-width: 700px;
    }
    .card-body{
        padding: 20px;
        width: 100%;
    }
</style>